name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1


      - name: Build Docker image
        run: docker build -t my-flask-app .

      - name: Run Docker container for testing
        run: docker run -d -p 5000:5000 --name my-flask-container my-flask-app

      - name: Wait for the application to start
        run: sleep 10

      - name: Run tests against the running container
        run: docker exec my-flask-container python -m pytest

      - name: Stop and remove the container
        run: docker stop my-flask-container && docker rm my-flask-container
